In [57]:
import pandas as pd
import numpy as np
import sklearn

In [58]:
data = pd.read_csv("main_dataset.csv")

C:\Users\asus\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [59]:
data = data[data[' Flow IAT Mean']>=0]
data = data[data[' Bwd IAT Std']>=0]

In [60]:
data.loc[data[' Label']!="BENIGN", ' Label'] = 1

In [61]:
data.loc[data[' Label']=="BENIGN", ' Label'] = 0
data.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,80,1870138,3,7,26,11607,20,0,8.666667,10.263203,...,20,0.0,0.0,0,0,0.0,0.0,0,0,1
1,80,11303671,4,0,24,0,6,6,6.000000,0.000000,...,20,6.0,0.0,6,6,11300000.0,0.0,11300000,11300000,1
2,59586,721234,5,2,11601,26,8760,0,2320.200000,3803.229575,...,20,0.0,0.0,0,0,0.0,0.0,0,0,0
3,80,834628,3,4,26,11601,20,0,8.666667,10.263203,...,20,0.0,0.0,0,0,0.0,0.0,0,0,1
4,80,104877,3,5,26,11607,20,0,8.666667,10.263203,...,20,0.0,0.0,0,0,0.0,0.0,0,0,1

In [62]:
train = data.sample(frac=0.8,random_state=303)
test = data.drop(train.index)

In [63]:
train.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
32464,443,5285344,5,1,135,46,46,6,27.000000,20.124612,...,20,249499.0,0.0,249499,249499,5023474.0,0.0,5023474,5023474,0
7967,80,109274,3,5,26,11607,20,0,8.666667,10.263203,...,20,0.0,0.0,0,0,0.0,0.0,0,0,1
62042,53,195,2,2,92,124,46,46,46.000000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,0
172419,80,85438223,8,5,294,11595,294,0,36.750000,103.944697,...,32,987.0,0.0,987,987,85300000.0,0.0,85300000,85300000,1
140857,21,8536849,9,15,105,188,23,0,11.666667,9.313968,...,32,0.0,0.0,0,0,0.0,0.0,0,0,1

In [64]:
train[' Label'].value_counts()

0    84419
1    66728
Name:  Label, dtype: int64

In [65]:
test[' Label'].value_counts()

0    20963
1    16824
Name:  Label, dtype: int64

In [66]:
X_train = train.iloc[:,:78]
X_train.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
32464,443,5285344,5,1,135,46,46,6,27.000000,20.124612,...,4,20,249499.0,0.0,249499,249499,5023474.0,0.0,5023474,5023474
7967,80,109274,3,5,26,11607,20,0,8.666667,10.263203,...,2,20,0.0,0.0,0,0,0.0,0.0,0,0
62042,53,195,2,2,92,124,46,46,46.000000,0.000000,...,1,20,0.0,0.0,0,0,0.0,0.0,0,0
172419,80,85438223,8,5,294,11595,294,0,36.750000,103.944697,...,1,32,987.0,0.0,987,987,85300000.0,0.0,85300000,85300000
140857,21,8536849,9,15,105,188,23,0,11.666667,9.313968,...,6,32,0.0,0.0,0,0,0.0,0.0,0,0

In [67]:
Y_train = train.iloc[:,78:79]
X_test = test.iloc[:,:78]
Y_test = test.iloc[:,78:79]
Y_train.head()

         Label
32464        0
7967         1
62042        0
172419       1
140857       1

In [68]:
Y_train.describe()

               Label
count  151147.000000
mean        0.441478
std         0.496565
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         1.000000

In [69]:
print('Training set:')
for col_name in data.columns:
    if data[col_name].dtypes == 'object' :
        unique_cat = len(data[col_name].unique())
        print("Feature '{col_name}' has {unique_cat} categories".format(col_name=col_name, unique_cat=unique_cat))

Training set:
Feature 'Flow Bytes/s' has 119125 categories
Feature ' Flow Packets/s' has 113101 categories

In [70]:
Y_test.head()

     Label
0        1
14       1
16       1
21       0
23       1

In [71]:
X_columns = [' Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', 'Bwd Packet Length Max',
       ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
       ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
       ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
       'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
       ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
       ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
       ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
       ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
       ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
       ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count',
       ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count',
       ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count',
       ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size',
       ' Avg Fwd Segment Size', ' Avg Bwd Segment Size',
       ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk',
       ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes',
       ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       ' Init_Win_bytes_backward', ' act_data_pkt_fwd',
       ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max',
       ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min']
Y_columns = [' Label']

In [72]:
X_train = X_train[pd.notnull(X_train[X_columns])]
X_test = X_test[pd.notnull(X_test[X_columns])]
Y_train = Y_train[pd .notnull(Y_train[Y_columns])]
Y_test = Y_test[pd.notnull(Y_test[Y_columns])]

In [73]:
X_train.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
32464,443,5285344,5,1,135,46,46,6,27.000000,20.124612,...,4,20,249499.0,0.0,249499,249499,5023474.0,0.0,5023474,5023474
7967,80,109274,3,5,26,11607,20,0,8.666667,10.263203,...,2,20,0.0,0.0,0,0,0.0,0.0,0,0
62042,53,195,2,2,92,124,46,46,46.000000,0.000000,...,1,20,0.0,0.0,0,0,0.0,0.0,0,0
172419,80,85438223,8,5,294,11595,294,0,36.750000,103.944697,...,1,32,987.0,0.0,987,987,85300000.0,0.0,85300000,85300000
140857,21,8536849,9,15,105,188,23,0,11.666667,9.313968,...,6,32,0.0,0.0,0,0,0.0,0.0,0,0

In [74]:
X_test.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
0,80,1870138,3,7,26,11607,20,0,8.666667,10.263203,...,2,20,0.0,0.0,0,0,0.0,0.0,0,0
14,80,78854260,9,7,62,11601,20,0,6.888889,5.301991,...,7,20,38859.0,0.0,38859,38859,38500000.0,42100000.0,68300000,8714914
16,80,84268687,8,5,56,11607,20,0,7.000000,5.656854,...,6,20,1000.0,0.0,1000,1000,41300000.0,44800000.0,73000000,9643868
21,443,4476246,5,1,135,46,46,6,27.000000,20.124612,...,4,20,0.0,0.0,0,0,0.0,0.0,0,0
23,80,50261,3,6,26,11601,20,0,8.666667,10.263203,...,2,20,0.0,0.0,0,0,0.0,0.0,0,0

In [75]:
Y_train.head()

         Label
32464        0
7967         1
62042        0
172419       1
140857       1

In [76]:
Y_test.head()

     Label
0        1
14       1
16       1
21       0
23       1

In [77]:
X_train.shape

(151147, 78)

In [78]:
Y_train.shape

(151147, 1)

In [79]:
X_test.shape

(37787, 78)

In [80]:
Y_test.shape

(37787, 1)

In [81]:
X_train.columns

Index([' Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', 'Bwd Packet Length Max',
       ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
       ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
       ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
       'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
       ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
       ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
       ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
       ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
       ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
       ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count',
       ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count',
       ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count',
       ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size',
       ' Avg Fwd Segment Size', ' Avg Bwd Segment Size',
       ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk',
       ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes',
       ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       ' Init_Win_bytes_backward', ' act_data_pkt_fwd',
       ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max',
       ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min'],
      dtype='object')

In [82]:
colNames = list(X_train)
colNames

[' Destination Port',
 ' Flow Duration',
 ' Total Fwd Packets',
 ' Total Backward Packets',
 'Total Length of Fwd Packets',
 ' Total Length of Bwd Packets',
 ' Fwd Packet Length Max',
 ' Fwd Packet Length Min',
 ' Fwd Packet Length Mean',
 ' Fwd Packet Length Std',
 'Bwd Packet Length Max',
 ' Bwd Packet Length Min',
 ' Bwd Packet Length Mean',
 ' Bwd Packet Length Std',
 'Flow Bytes/s',
 ' Flow Packets/s',
 ' Flow IAT Mean',
 ' Flow IAT Std',
 ' Flow IAT Max',
 ' Flow IAT Min',
 'Fwd IAT Total',
 ' Fwd IAT Mean',
 ' Fwd IAT Std',
 ' Fwd IAT Max',
 ' Fwd IAT Min',
 'Bwd IAT Total',
 ' Bwd IAT Mean',
 ' Bwd IAT Std',
 ' Bwd IAT Max',
 ' Bwd IAT Min',
 'Fwd PSH Flags',
 ' Bwd PSH Flags',
 ' Fwd URG Flags',
 ' Bwd URG Flags',
 ' Fwd Header Length',
 ' Bwd Header Length',
 'Fwd Packets/s',
 ' Bwd Packets/s',
 ' Min Packet Length',
 ' Max Packet Length',
 ' Packet Length Mean',
 ' Packet Length Std',
 ' Packet Length Variance',
 'FIN Flag Count',
 ' SYN Flag Count',
 ' RST Flag Count',
 ' PSH Flag Count',
 ' ACK Flag Count',
 ' URG Flag Count',
 ' CWE Flag Count',
 ' ECE Flag Count',
 ' Down/Up Ratio',
 ' Average Packet Size',
 ' Avg Fwd Segment Size',
 ' Avg Bwd Segment Size',
 ' Fwd Header Length.1',
 'Fwd Avg Bytes/Bulk',
 ' Fwd Avg Packets/Bulk',
 ' Fwd Avg Bulk Rate',
 ' Bwd Avg Bytes/Bulk',
 ' Bwd Avg Packets/Bulk',
 'Bwd Avg Bulk Rate',
 'Subflow Fwd Packets',
 ' Subflow Fwd Bytes',
 ' Subflow Bwd Packets',
 ' Subflow Bwd Bytes',
 'Init_Win_bytes_forward',
 ' Init_Win_bytes_backward',
 ' act_data_pkt_fwd',
 ' min_seg_size_forward',
 'Active Mean',
 ' Active Std',
 ' Active Max',
 ' Active Min',
 'Idle Mean',
 ' Idle Std',
 ' Idle Max',
 ' Idle Min']

In [83]:
from sklearn.preprocessing import Imputer


X_train = Imputer().fit_transform(X_train)
X_test = Imputer().fit_transform(X_test)

C:\Users\asus\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
C:\Users\asus\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

In [84]:
X_train.shape

(151147, 76)

In [85]:
X_test.shape

(37787, 76)

In [90]:
from sklearn.feature_selection import SelectPercentile, f_classif

selector=SelectPercentile(f_classif, percentile=10)
X_newtrain = selector.fit_transform(X_train,Y_train)
X_newtrain.shape

C:\Users\asus\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\asus\Anaconda3\lib\site-packages\sklearn\feature_selection\univariate_selection.py:114: UserWarning: Features [29 31 54 55 56 57 58 59] are constant.
  UserWarning)
C:\Users\asus\Anaconda3\lib\site-packages\sklearn\feature_selection\univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw

(151147, 8)

In [91]:
selector=SelectPercentile(f_classif, percentile=10)
X_newtest = selector.fit_transform(X_test,Y_test)
X_newtest.shape

C:\Users\asus\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\asus\Anaconda3\lib\site-packages\sklearn\feature_selection\univariate_selection.py:114: UserWarning: Features [29 31 54 55 56 57 58 59] are constant.
  UserWarning)
C:\Users\asus\Anaconda3\lib\site-packages\sklearn\feature_selection\univariate_selection.py:115: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw

(37787, 8)

In [93]:
true=selector.get_support()
X_trainnewcolindex=[i for i, x in enumerate(true) if x]
X_trainnewcolname=list( colNames[i] for i in X_trainnewcolindex )
X_trainnewcolname

['Bwd Packet Length Max',
 ' Bwd Packet Length Min',
 ' Bwd Packet Length Mean',
 ' Bwd Packet Length Std',
 'Fwd Packets/s',
 ' Bwd Packets/s',
 ' Max Packet Length',
 ' Average Packet Size']

In [92]:
#with a naive bayes
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC


clf = MultinomialNB().fit(X_newtrain, Y_train)
print("naive bayes accuracy is")

#step 4: evaluate classifier

print(clf.score(X_newtest, Y_test))

naive bayes accuracy is
0.6426284171805118

C:\Users\asus\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)