In [416]:
import pandas as pd
import numpy as np
import sklearn

In [417]:
data = pd.read_csv("main_dataset.csv")

/home/dayamish/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [418]:
data.loc[data[' Label']!="BENIGN", ' Label'] = 1

In [419]:
data.loc[data[' Label']=="BENIGN", ' Label'] = 0
data.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,80,1870155,3,7,26,11607,20,0,8.666667,10.263203,...,536870681,0.0,0.0,0,0,0.0,0.0,0,0,1
1,80,11303688,4,0,24,0,6,6,6.000000,0.000000,...,536870681,6.0,0.0,6,6,11300000.0,0.0,11300000,11300000,1
2,59586,721251,5,2,11601,26,8760,0,2320.200000,3803.229575,...,536870681,0.0,0.0,0,0,0.0,0.0,0,0,0
3,80,834645,3,4,26,11601,20,0,8.666667,10.263203,...,536870681,0.0,0.0,0,0,0.0,0.0,0,0,1
4,80,104894,3,5,26,11607,20,0,8.666667,10.263203,...,536870681,0.0,0.0,0,0,0.0,0.0,0,0,1

In [420]:
train = data.sample(frac=0.8,random_state=303)
test = data.drop(train.index)

In [321]:
train.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
183233,21,63,1,2,0,0,0,0,0.000000,0.000000,...,536870681,0.00000,0.0000,0,0,0.000,0.000,0,0,BENIGN
169391,53,166833,4,2,328,260,82,82,82.000000,0.000000,...,536870681,0.00000,0.0000,0,0,0.000,0.000,0,0,BENIGN
36580,1002,90,1,1,2,6,2,2,2.000000,0.000000,...,536870685,0.00000,0.0000,0,0,0.000,0.000,0,0,PortScan
110988,63605,9354,2,0,6,0,6,0,3.000000,4.242641,...,536870681,0.00000,0.0000,0,0,0.000,0.000,0,0,BENIGN
745,443,116403788,22,19,1079,3669,389,0,49.045455,110.418027,...,536870681,71591.66667,149264.4828,545570,28337,9628722.333,1274584.255,10000000,5581644,BENIGN

In [421]:

train[' Label'].value_counts()

0    143024
1     39427
Name:  Label, dtype: int64

In [135]:

test[' Label'].value_counts()

BENIGN                        35572
DDoS                           3918
PortScan                       3223
DoS Hulk                       2353
DoS GoldenEye                    96
Web Attack ï¿½ Brute Force         84
FTP-Patator                      81
SSH-Patator                      70
DoS Slowhttptest                 62
DoS slowloris                    61
Bot                              58
Web Attack ï¿½ XSS                 32
Web Attack ï¿½ Sql Injection        2
Infiltration                      1
Name:  Label, dtype: int64

In [422]:
X_train = train.iloc[:,:78]
X_train.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
183233,21,63,1,2,0,0,0,0,0.000000,0.000000,...,0,536870681,0.00000,0.0000,0,0,0.000,0.000,0,0
169391,53,166833,4,2,328,260,82,82,82.000000,0.000000,...,3,536870681,0.00000,0.0000,0,0,0.000,0.000,0,0
36580,1002,90,1,1,2,6,2,2,2.000000,0.000000,...,0,536870685,0.00000,0.0000,0,0,0.000,0.000,0,0
110988,63605,9354,2,0,6,0,6,0,3.000000,4.242641,...,1,536870681,0.00000,0.0000,0,0,0.000,0.000,0,0
745,443,116403788,22,19,1079,3669,389,0,49.045455,110.418027,...,21,536870681,71591.66667,149264.4828,545570,28337,9628722.333,1274584.255,10000000,5581644

In [423]:
Y_train = train.iloc[:,78:79]
X_test = test.iloc[:,:78]
Y_test = test.iloc[:,78:79]
Y_train.head()

         Label
183233       0
169391       0
36580        1
110988       0
745          0

In [424]:
Y_train.describe()

               Label
count  182451.000000
mean        0.216096
std         0.411582
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000

In [425]:
data[' Label'].value_counts()

0    178596
1     49468
Name:  Label, dtype: int64

In [85]:
print('Training set:')
for col_name in data.columns:
    if data[col_name].dtypes == 'object' :
        unique_cat = len(data[col_name].unique())
        print("Feature '{col_name}' has {unique_cat} categories".format(col_name=col_name, unique_cat=unique_cat))

#see how distributed the feature service is, it is evenly distributed and therefore we need to make dummies for all.

Training set:
Feature 'Flow Bytes/s' has 145650 categories
Feature ' Flow Packets/s' has 123030 categories
Feature ' Label' has 15 categories

In [89]:
Y_test.head()

     Label
0     DDoS
14    DDoS
16    DDoS
21  BENIGN
23    DDoS

In [90]:
from sklearn import model_selection, preprocessing
label_encoder = preprocessing.LabelEncoder()
#Y_train = label_encoder.fit_transform(Y_train[' Label'])
#Y_train

In [91]:
#Y_test = label_encoder.fit_transform(Y_test[' Label'])
#Y_test

In [426]:
X_columns = [' Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', 'Bwd Packet Length Max',
       ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
       ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
       ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
       'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
       ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
       ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
       ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
       ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
       ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
       ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count',
       ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count',
       ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count',
       ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size',
       ' Avg Fwd Segment Size', ' Avg Bwd Segment Size',
       ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk',
       ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes',
       ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       ' Init_Win_bytes_backward', ' act_data_pkt_fwd',
       ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max',
       ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min']
Y_columns = [' Label']

In [427]:
X_train = X_train[pd.notnull(X_train[X_columns])]
X_test = X_test[pd.notnull(X_test[X_columns])]
Y_train = Y_train[pd .notnull(Y_train[Y_columns])]
Y_test = Y_test[pd.notnull(Y_test[Y_columns])]

In [428]:
X_train.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
183233,21,63,1,2,0,0,0,0,0.000000,0.000000,...,0,536870681,0.00000,0.0000,0,0,0.000,0.000,0,0
169391,53,166833,4,2,328,260,82,82,82.000000,0.000000,...,3,536870681,0.00000,0.0000,0,0,0.000,0.000,0,0
36580,1002,90,1,1,2,6,2,2,2.000000,0.000000,...,0,536870685,0.00000,0.0000,0,0,0.000,0.000,0,0
110988,63605,9354,2,0,6,0,6,0,3.000000,4.242641,...,1,536870681,0.00000,0.0000,0,0,0.000,0.000,0,0
745,443,116403788,22,19,1079,3669,389,0,49.045455,110.418027,...,21,536870681,71591.66667,149264.4828,545570,28337,9628722.333,1274584.255,10000000,5581644

In [429]:
X_test.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
0,80,1870155,3,7,26,11607,20,0,8.666667,10.263203,...,2,536870681,0.0,0.0,0,0,0.0,0.0,0,0
14,80,78854277,9,7,62,11601,20,0,6.888889,5.301991,...,7,536870681,38859.0,0.0,38859,38859,38500000.0,42100000.0,68300000,8714914
16,80,84268704,8,5,56,11607,20,0,7.000000,5.656854,...,6,536870681,1000.0,0.0,1000,1000,41300000.0,44800000.0,73000000,9643868
21,443,4476263,5,1,135,46,46,6,27.000000,20.124612,...,4,536870681,0.0,0.0,0,0,0.0,0.0,0,0
23,80,50278,3,6,26,11601,20,0,8.666667,10.263203,...,2,536870681,0.0,0.0,0,0,0.0,0.0,0,0

In [430]:
Y_train.head()

         Label
183233       0
169391       0
36580        1
110988       0
745          0

In [431]:
Y_test.head()

     Label
0        1
14       1
16       1
21       0
23       1

In [98]:
Y_train.describe()

         Label
count   182451
unique      15
top     BENIGN
freq    143024

In [432]:
X_train.shape

(182451, 78)

In [433]:
Y_train.shape

(182451, 1)

In [434]:
X_test.shape

(45613, 78)

In [435]:
Y_test.shape

(45613, 1)

In [436]:
X_train.columns

Index([' Destination Port', ' Flow Duration', ' Total Fwd Packets',
       ' Total Backward Packets', 'Total Length of Fwd Packets',
       ' Total Length of Bwd Packets', ' Fwd Packet Length Max',
       ' Fwd Packet Length Min', ' Fwd Packet Length Mean',
       ' Fwd Packet Length Std', 'Bwd Packet Length Max',
       ' Bwd Packet Length Min', ' Bwd Packet Length Mean',
       ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s',
       ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min',
       'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max',
       ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std',
       ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags',
       ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length',
       ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s',
       ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean',
       ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count',
       ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count',
       ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count',
       ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size',
       ' Avg Fwd Segment Size', ' Avg Bwd Segment Size',
       ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk',
       ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk',
       'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes',
       ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       ' Init_Win_bytes_backward', ' act_data_pkt_fwd',
       ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max',
       ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min'],
      dtype='object')

In [437]:
colNames = list(X_train)
colNames

[' Destination Port',
 ' Flow Duration',
 ' Total Fwd Packets',
 ' Total Backward Packets',
 'Total Length of Fwd Packets',
 ' Total Length of Bwd Packets',
 ' Fwd Packet Length Max',
 ' Fwd Packet Length Min',
 ' Fwd Packet Length Mean',
 ' Fwd Packet Length Std',
 'Bwd Packet Length Max',
 ' Bwd Packet Length Min',
 ' Bwd Packet Length Mean',
 ' Bwd Packet Length Std',
 'Flow Bytes/s',
 ' Flow Packets/s',
 ' Flow IAT Mean',
 ' Flow IAT Std',
 ' Flow IAT Max',
 ' Flow IAT Min',
 'Fwd IAT Total',
 ' Fwd IAT Mean',
 ' Fwd IAT Std',
 ' Fwd IAT Max',
 ' Fwd IAT Min',
 'Bwd IAT Total',
 ' Bwd IAT Mean',
 ' Bwd IAT Std',
 ' Bwd IAT Max',
 ' Bwd IAT Min',
 'Fwd PSH Flags',
 ' Bwd PSH Flags',
 ' Fwd URG Flags',
 ' Bwd URG Flags',
 ' Fwd Header Length',
 ' Bwd Header Length',
 'Fwd Packets/s',
 ' Bwd Packets/s',
 ' Min Packet Length',
 ' Max Packet Length',
 ' Packet Length Mean',
 ' Packet Length Std',
 ' Packet Length Variance',
 'FIN Flag Count',
 ' SYN Flag Count',
 ' RST Flag Count',
 ' PSH Flag Count',
 ' ACK Flag Count',
 ' URG Flag Count',
 ' CWE Flag Count',
 ' ECE Flag Count',
 ' Down/Up Ratio',
 ' Average Packet Size',
 ' Avg Fwd Segment Size',
 ' Avg Bwd Segment Size',
 ' Fwd Header Length.1',
 'Fwd Avg Bytes/Bulk',
 ' Fwd Avg Packets/Bulk',
 ' Fwd Avg Bulk Rate',
 ' Bwd Avg Bytes/Bulk',
 ' Bwd Avg Packets/Bulk',
 'Bwd Avg Bulk Rate',
 'Subflow Fwd Packets',
 ' Subflow Fwd Bytes',
 ' Subflow Bwd Packets',
 ' Subflow Bwd Bytes',
 'Init_Win_bytes_forward',
 ' Init_Win_bytes_backward',
 ' act_data_pkt_fwd',
 ' min_seg_size_forward',
 'Active Mean',
 ' Active Std',
 ' Active Max',
 ' Active Min',
 'Idle Mean',
 ' Idle Std',
 ' Idle Max',
 ' Idle Min']

In [440]:
from sklearn.preprocessing import Imputer


X_train = Imputer().fit_transform(X_train)
X_test = Imputer().fit_transform(X_test)

In [441]:
X_train.shape

(182451, 76)

In [442]:
X_test.shape

(45613, 76)

In [492]:
from sklearn.feature_selection import SelectPercentile, f_classif

selector=SelectPercentile(f_classif, percentile=9)
X_newtrain = selector.fit_transform(X_train,Y_train)
X_newtrain.shape

/home/dayamish/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/dayamish/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:113: UserWarning: Features [29 31 54 55 56 57 58 59] are constant.
  UserWarning)
/home/dayamish/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw

(182451, 7)

In [493]:
selector=SelectPercentile(f_classif, percentile=9)
X_newtest = selector.fit_transform(X_test,Y_test)
X_newtest.shape

/home/dayamish/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/dayamish/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:113: UserWarning: Features [29 31 54 55 56 57 58 59] are constant.
  UserWarning)
/home/dayamish/anaconda3/lib/python3.6/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw

(45613, 7)

In [445]:

true=selector.get_support()
X_trainnewcolindex=[i for i, x in enumerate(true) if x]
X_trainnewcolname=list( colNames[i] for i in X_trainnewcolindex )
X_trainnewcolname

['Bwd Packet Length Max',
 ' Bwd Packet Length Mean',
 ' Bwd Packet Length Std',
 ' Bwd Packets/s',
 ' Max Packet Length',
 ' Packet Length Mean',
 ' ECE Flag Count',
 ' Average Packet Size']

In [494]:
#with a naive bayes
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC


clf = MultinomialNB().fit(X_newtrain, Y_train)
print("naive bayes accuracy is")

#step 4: evaluate classifier

print(clf.score(X_newtest, Y_test))

naive bayes accuracy is
0.8411417797557714

/home/dayamish/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [311]:
data.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,80.0,1870138.0,3,7.0,26.0,11607.0,20.0,NaN,8.666667,10.263203,...,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DDoS
1,80.0,11303671.0,4,NaN,24.0,NaN,6.0,6.0,6.000000,NaN,...,20.0,6.0,NaN,6.0,6.0,11300000.0,NaN,11300000.0,11300000.0,DDoS
2,59586.0,721234.0,5,2.0,11601.0,26.0,8760.0,NaN,2320.200000,3803.229575,...,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BENIGN
3,80.0,834628.0,3,4.0,26.0,11601.0,20.0,NaN,8.666667,10.263203,...,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DDoS
4,80.0,104877.0,3,5.0,26.0,11607.0,20.0,NaN,8.666667,10.263203,...,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DDoS